import { ThemeProvider } from "@components/theme-provider";
import { Button } from "@components/ui/button";
import { ModeToggle } from "@components/ui/mode-toggle";
import Link from "next/link";
import { ProfileDropdown } from "../components/profile-dropdown";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="min-h-screen bg-background flex flex-col p-5">
            <nav className="flex justify-between w-full">
              <Link href="/">
                <Button variant="outline">Dashboard</Button>
              </Link>
              <div className="ml-auto flex align-items-center gap-5">
                <ProfileDropdown />
                <ModeToggle />
              </div>
            </nav>
            <div className="py-5">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
